# Generated by Django 4.1 on 2022-08-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='today_offer',
            field=models.BooleanField(default=False),
        ),
    ]
