# Generated by Django 4.1.1 on 2022-09-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_rename_variation_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
