# Generated by Django 4.1.1 on 2022-09-22 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_rename_variations_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variation',
            new_name='variations',
        ),
    ]
