# Generated by Django 4.1 on 2022-08-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_phone_number_userprofile_mobile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='mobile_phone',
            new_name='phone_number',
        ),
    ]
