# Generated by Django 4.1 on 2022-08-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_veruthe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='veruthe',
        ),
    ]
